version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: org.codehaus.groovy:groovy
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/plugin"
    schedule:
      interval: "weekly"
    groups:
      javascript-version:
        applies-to: version-updates
      javascript-security:
        applies-to: security-updates
